app_home:
    path:      /
    defaults: { _controller: AppBundle:Default:home }

app_login:
    path:      /login
    defaults: { _controller: AppBundle:Default:login }

app_subscribe:
    path:      /subscribe
    defaults: { _controller: AppBundle:Default:subscribe }


app_my_adverts:
    path:      /adverts
    defaults: { _controller: AppBundle:Default:myAdverts }

app_dashboard:
    path:      /dashboard
    defaults: { _controller: AppBundle:Default:dashboard }

app_mailbox:
    path:      /mailbox
    defaults: { _controller: AppBundle:Default:mailbox }

app_try_list:
    path:      /try-list
    defaults: { _controller: AppBundle:Default:tryList }

app_advert_calendar:
    path:      /advert-calendar
    defaults: { _controller: AppBundle:Default:advertCalendar }

app_my_account:
    path:      /my-account
    defaults: { _controller: AppBundle:Default:myAccount }

