esay_test_home:
    path:      /
    defaults: { _controller: AppBundle:Default:home }

app_login:
    path:      /login
    defaults: { _controller: AppBundle:Default:login }

app_subscribe:
    path:      /subscribe
    defaults: { _controller: AppBundle:Default:subscribe }


app_my_adverts:
    path:      /adverts
    defaults: { _controller: AppBundle:Default:myAdverts }

