app_home:
    path:      /
    defaults: { _controller: AppBundle:Default:home }

app_login:
    path:      /login
    defaults: { _controller: AppBundle:Default:login }

app_subscribe:
    path:      /subscribe
    defaults: { _controller: AppBundle:Default:subscribe }


app_my_adverts:
    path:      /adverts
    defaults: { _controller: AppBundle:Default:myAdverts }

app_dashboard:
    path:      /dashboard
    defaults: { _controller: AppBundle:Default:dashboard }

app_mailbox:
    path:      /mailbox
    defaults: { _controller: AppBundle:Default:mailbox }

